### ISSUE TITLE
Could not send Message.

### ISSUE THREAD

**Issue by PMbatha** [BingAds/BingAds-Java-SDK#102]
We are making calls to the Bind Ad API - "Bing Ads API v11" (KeywordPerformanceReport + ProductSearchQueryPerformanceReport)

We are now getting the following error:

javax.xml.ws.WebServiceException: Could not send Message. at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:149) at com.sun.proxy.$Proxy282.submitGenerateReport(Unknown Source) at com.impact.cis.impl.bing.downloader.ReportDownloader.submitReportRequest(ReportDownloader.java:243) at com.impact.cis.impl.bing.downloader.ReportDownloader.downloadReportAsString(ReportDownloader.java:93) at com.impact.cis.impl.bing.downloader.ReportDownloader.downloadCostData(ReportDownloader.java:138) at com.impact.cis.impl.bing.downloader.ReportDownloader.downloadCostData(ReportDownloader.java:151) at com.impact.cis.impl.bing.downloader.ReportDownloader$DownloadMultipleConsumer.accept(ReportDownloader.java:82) at com.impact.cis.impl.bing.downloader.ReportDownloader$DownloadMultipleConsumer.accept(ReportDownloader.java:64) at java.util.ArrayList.forEach(ArrayList.java:1249) at com.impact.cis.impl.bing.downloader.ReportDownloader.download(ReportDownloader.java:168) at com.impact.cis.impl.bing.BingAdImporter.extract(BingAdImporter.java:76) at com.impact.cis.impl.bing.BingAdImporter.extract(BingAdImporter.java:35) at com.impact.cis.common.Importer.processExtraction(Importer.java:283) at com.impact.cis.common.Importer.execute(Importer.java:114) at com.impact.cis.JmsQueueListener.processCostImportAccount(JmsQueueListener.java:49) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:180) at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:112) at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:104) at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:69) at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:719) at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:679) at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:649) at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317) at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:255) at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1166) at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1158) at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1055) at java.lang.Thread.run(Thread.java:748) Caused by: org.apache.cxf.transport.http.HTTPException: HTTP response '503: Service Unavailable' when communicating with https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/v12/ReportingService.svc at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1611) at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1618) at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1559) at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1356) at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:653) at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62) at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:520) at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:429) at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:330) at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:283) at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96) at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:138) ... 31 more

**Comment by qitia** [comment]
hey @PMbatha are you using the lib here? I do not think you can still access Api V11 any more. Api V11 has been officially deprecated already.

**Comment by PMbatha** [comment]
@qitia - Apologies, just checked our Code Base we are using API Version 12.0.1 - What are the normal causes for the above issues?

**Comment by qitia** [comment]
@PMbatha seems you are not using the sdk here(**com.impact.cis.impl.bing.downloader.**ReportDownloader) in this git repo, are you? Could you please share more detail to repro?

**Comment by qingjuntian** [comment]
Close as not related. @PMbatha you can reopen it in case other concern. BTW we have release the latest SDK 13.0.1. If you are not using that yet. I recommend you to give it a try.
