### ISSUE TITLE
What are the enum values for AssetLink#pinnedField ?

### ISSUE THREAD

**Issue by markusheiden** [BingAds/BingAds-Java-SDK#105]
We are trying to implement RSAs. But for setting the pins I am not able to find any documentation on how to set the pin (AssetLink#pinnedField). Since the pins are currently just strings, may you please give me the valid values?

**Comment by qitia** [comment]
hi @markusheiden we have doc it here: https://docs.microsoft.com/en-us/advertising/campaign-management-service/assetlink?view=bingads-13. Please let us know if this not enough.

**Comment by markusheiden** [comment]
They are a bit hidden inside a longer text, so I overlooked them, sorry.
