### ISSUE TITLE
Type of TextAsset is missing

### ISSUE THREAD

**Issue by markusheiden** [BingAds/BingAds-Java-SDK#107]
I am trying to create RSAs but the headlines and descriptions are not written to the bulk csv. I found that the type of TextAsset won't be automatically set to "TextAsset". So StringExtensions.toTextAssetLinksBulkString does not extract them and they are not written to the csv. Maybe StringExtensions.toTextAssetLinksBulkString should use "instanceof TextAsset" instead of checking type to be "TextAsset"?

**Comment by markusheiden** [comment]
If I set the type manually to "TextAsset", StringExtensions.toTextAssetLinksBulkString fails, if the text asset has no id. That is because TextAssetLinkContract.id is not nullable (primitive type long) and Asset.id is not nullable (object type Long).

Regarding the documentation, both the type and the id are read-only, so they should be optional. Did this code ever work for you?

**Comment by eric-urban** [comment]
@markusheiden you are correct, thanks! I can repro the same issue, and your PR works for me. We'll need to fix this in both v12 and v13 for text and image assets. We'll update this thread when the release ETA is confirmed e.g., next week. 

@qitia FYI

**Comment by qitia** [comment]
hi @markusheiden version [12.13.4.1](https://github.com/BingAds/BingAds-Java-SDK/releases/tag/v12.13.4.1) has been published today. Thanks for the PR.

**Comment by qitia** [comment]
@markusheiden We updated com.fasterxml.jackson.core, artifact jackson-databind version from 2.9.9.2 to 2.9.9.3 due to [issue 2395](https://github.com/FasterXML/jackson-databind/issues/2395) in version 12.13.4.2, please try this version in need.
