### ISSUE TITLE
Add the ability to work behind a Web Proxy

### ISSUE THREAD

**Issue by yosefarr** [BingAds/BingAds-Java-SDK#11]
Hi,
I have a problem to Invoke API calls when my client sets behind a Web Proxy
I already add a Fork to the SDK that add this ability using system properties

Please review and update if there is an exist option to do that

Thanks,
Yosef

**Comment by OhadR** [comment]
is there a plan to merge the fix?

**Comment by shyTNT** [comment]
@OhadR yes, we will merge it this month. Thank you.

**Comment by shyTNT** [comment]
@yosefarr  Thanks for your contribution. We will merge your code in next release. We also resolved other issue about SDK work behind a Web Proxy. Thank you again.

**Comment by shyTNT** [comment]
@yosefarr  The Java SDK 10.4.3 has been released. Thanks for your contribution again!
