### ISSUE TITLE
Support For EditorialAppealStatus, Editorial Location, Editorial Reason Codes, Editorial Term for Ads and Keywords?

### ISSUE THREAD

**Issue by pavan-kalyan** [BingAds/BingAds-Java-SDK#116]
The Docs [here](https://docs.microsoft.com/en-us/advertising/bulk-service/keyword?view=bingads-13#editorialappealstatus) suggest that the API returns these values in the bulk file schema, but the SDK doesn't seem to support this.

Are the Docs wrong? or is it that the SDK currently doesn't support it, are there any plans to support these values?

Any clarification on this could be helpful to me, thanks.

**Comment by qitia** [comment]
I think it should be in the BulkAd.Errors or BulkKeyword.Errors. See [BulkError](https://github.com/BingAds/BingAds-Java-SDK/blob/main/src/main/java/com/microsoft/bingads/v13/bulk/entities/BulkError.java) for detail.
