### ISSUE TITLE
Mapping for StringTable.PromotionAdExtension missing in StaticBulkObjectFactory

### ISSUE THREAD

**Issue by schabe77** [BingAds/BingAds-Java-SDK#117]
Hi,

when try to upload PromotionAdExtension a get a UnknownBulkEntity instead of a PromotionAdExtension as response and the requested operation hasn't been done.

After debugging the communication between client and server I found out, that the client doesn't provide the entity type on upload and that's because no mapping for PromotionAdExtension is contained in StaticBulkObjectFactory.

Could you please add this mapping? Otherwise I'm not able to upload promotions.

Thanks

Christian

**Comment by schabe77** [comment]
I just found out that the upload seems to go wrong on purpose. When I try uploading the promotions including a valid type, I get the BulkError: AdExtensionPilotNotEnabledForCustomer

**Comment by qitia** [comment]
thanks for reaching. you are right PromotionAdExtension was missing in the factory. I will send a fix soon.

**Comment by qitia** [comment]
Version 13.0.8 has fixed this issue. please try it out.
