### ISSUE TITLE
Bing Ads Java requires CXF but does not fail if used with JAXWS-RI

### ISSUE THREAD

**Issue by markusheiden** [BingAds/BingAds-Java-SDK#120]
We are developing a tool which uses AdWords and Bing Ads API. Both libs provide a JAXWS implementation. AdWords provides JAXWS-RI and Bing Ads provides CXF. So if not managed manually, that leads to an unpredictable behavior which runtime gets used, because the first one in the classpath will be used.

At least the reporting queries always fail with "100, NullRequest, The request message is null", if JAXWS-RI is used as JAXWS implementation.

So it would be nice, if a) Bing Ads API works with JAXWS-RI too or b) Bing Ads fails if the JAXWS implementation is not CXF. 

Furthermore it would be nice, if a more recent version of CXF (at least 3.3.8, or 3.4.1 if possible) would be used.
For jakarta.jws-api version 2.1.0 would be nice, to not provoke version conflicts with AdWords.

**Comment by qitia** [comment]
Bing Ads lib by default uses CXF as jaxws implementation. You can also avoid use that by not including cxf lib in you pom.xml(if you are using maven)

**Comment by qitia** [comment]
hi @markusheiden - we published version 13.0.8 today and it is using more up-to-date lib as dependencies, please try this version. I would close this as resolved for now. Please let me know if you have more concern.
