### ISSUE TITLE
Campaign Service is not building due to missing operation in wsdl

### ISSUE THREAD

**Issue by keith-wiersema** [BingAds/BingAds-Java-SDK#121]
When upgrading to version 13.0.7 it seems the the campaign service can no longer be created. I am getting the following error:
```
Undefined operation name AddBidStrategies
```
Looking at the campaign service wsdl endpoint here: https://campaign.api.bingads.microsoft.com/Api/Advertiser/CampaignManagement/v13/CampaignManagementService.svc?wsdl
I can only see request and response headers for AddBidStrategies and no operation. Can you please update the wsdl accordingly? Thank you!

**Comment by eric-urban** [comment]
@keith-wiersema thanks for raising this issue. We will release version 13.0.7.1 soon with a fix.

**Comment by keith-wiersema** [comment]
This appears to be fixed with version 13.0.7.1, closing the issue.
