### ISSUE TITLE
Missing new languages

### ISSUE THREAD

**Issue by markusheiden** [BingAds/BingAds-Java-SDK#125]
The languages CZ, PL, SK should be supported in a pilot, which one of our customers has access to. But with the current SDK 13.8.0.1 I cannot use them because `com.microsoft.bingads.v13.customermanagement.LanguageType` does not know them. How can I use the new languages via the SDK?

**Comment by qitia** [comment]
we will release a new version 13.0.9 soon, with that you will be able to use latest proxies.
