### ISSUE TITLE
Support for Hotel Ads Bulk API

### ISSUE THREAD

**Issue by janjouketjalsma** [BingAds/BingAds-Java-SDK#133]
Is support for Hotel Ads Bulk API planned for the near future?
Hotel Ads Bulk API: https://docs.microsoft.com/en-us/advertising/guides/hotel-ads-bulk?view=bingads-13

As far as I can see the entities do not exist yet. I checked here https://github.com/BingAds/BingAds-Java-SDK/tree/main/src/main/java/com/microsoft/bingads/v13/bulk/entities .

**Comment by qitia** [comment]
yes we are working on that. please expect this feature coming soon.

**Comment by qitia** [comment]
this has been supported with latest version 13.0.15
