### ISSUE TITLE
Cannot set access token in OAuthWithAuthorizationCode

### ISSUE THREAD

**Issue by shannonlui** [BingAds/BingAds-Java-SDK#137]
The `OAuthWithAuthorizationCode` constructors are setting the `accessToken` to be null as seen in the source code:
```
    protected OAuthWithAuthorizationCode(String clientId, String clientSecret, URL redirectionUri, OAuthTokens oauthTokens, ApiEnvironment env, OAuthScope oAuthScope) {
        this(clientId, clientSecret, redirectionUri, env, oAuthScope);
        if (oauthTokens != null && oauthTokens.getRefreshToken() != null) {
            this.oAuthTokens = new OAuthTokens((String)null, 0L, oauthTokens.getRefreshToken());
        } else {
            throw new NullPointerException("OAuth tokens must not be null");
        }
    }
```

The `refreshTokensIfNeeded()` method in this class forces refresh when the access token is null. So this results in the token keep getting refreshed even though we have a valid access token stored but cannot pass to `OAuthWithAuthorizationCode`.

What is the intention behind this behaviour? Is it not a good idea to have the access token set in this class?

**Comment by shannonlui** [comment]
Our workaround is to extend the class to update the constructor to set the `accessToken` and `accessTokenExpiresInSeconds` with the values passed in through `oauthTokens`. But we want to understand why this wasn't done in the original implementation.

**Comment by qitia** [comment]
Thanks @shannonlui , I am also curious why is this design in the beginning. I will try update it.

**Comment by qitia** [comment]
I looked into the source code again and I think the original design is to make sure we have a valid access token, thus we let the library itself tries to refresh access token with Refreshtoken. I will keep it. If you are sure your access token is valid and do not want it get refreshed again, you can use the workaround.
