### ISSUE TITLE
Version supporting jakarta is missing

### ISSUE THREAD

**Issue by markusheiden** [BingAds/BingAds-Java-SDK#142]
The lib still uses `javax.xml.ws:jaxws-api` instead of the newer `jakarta.xml.ws:jakarta.xml.ws-api`. Are there plans for a migration? With Spring Boot 3 the support for the old lib has been dropped.

**Comment by qitia** [comment]
Fire ask. We will evaluate this.

**Comment by markusheiden** [comment]
Do you have any updates on this? This blocks our migration to Spring Boot 3.

**Comment by qitia** [comment]
Hi yes, the SDK vNext targets early June 2023. works for you?

**Comment by markusheiden** [comment]
Thanks for the fast answer!
That's quite some time ;-) but OK for us.

**Comment by qitia** [comment]
folks, v13.0.16 was released June/07(please use 13.0.16.1 as it fix a tiny issue, see release notes). from now on we start to support jakarta instead of jaxws. Please use this version. 

we also upgrade [pom.xml](https://github.com/BingAds/BingAds-Java-SDK/blob/main/examples/BingAdsDesktopApp/pom.xml) in the example. Please refer to it in case you have any dependent issue.

**Comment by markusheiden** [comment]
@qitia Currently, I am not able to test, because there is still a Hibernate bug that let our application fail.

There is still a dependency on `javax.activation` instead of `jakarta.activation`. I am not sure whether that may be a problem and cause conflicts if `jakarta.activation` (via Spring Boot 3+) is on the classpath too.

 In the `pom.xml` `jaxws-rt` is rather old: 3.0.0 is from 11/18/2020. IMO it should be at least 3.0.2, probably even 4.0.1. That applies to the version of other dependencies in the above-mentioned `pom.xml` and in the `pom.xml` of this lib too.

**Comment by qitia** [comment]
thanks. Let me double check.

**Comment by markusheiden** [comment]
A first test shows: The current version works fine with Spring Boot 3+ / Jakarta. Thanks a lot!

We will do more testing when the Hibernate problems mentioned above have been fixed in an official Hibernate release. So that may take some days.

**Comment by qitia** [comment]
Glad to know!

**Comment by qitia** [comment]
seems like we missed removing javax.activation, let me know if there is conflict, we can ship a quick release in that case.

for jaxws-rt in the example pom, I have update it to 4.0.1

**Comment by BenanMozalbet** [comment]
hii, i upgrade my bing ads sdk to use  pom xml version of 13.0.16.2 

 (previously, i used version: 13.0.15). now i start getting issue : 

java.lang.ClassNotFoundException: jakarta.xml.ws.spi.Provider. 


the below dependncies appear in 13.0.16.2, 
   <groupId>jakarta.jws</groupId>
            <artifactId>jakarta.jws-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.ws</groupId>
            <artifactId>jakarta.xml.ws-api</artifactId>
            <version>3.0.0</version>
        </dependency> 

any answer please, why this happen ?

**Comment by markusheiden** [comment]
This library has made the switch from using `javax.*` to `jakarta.*` with version `13.0.16.1`. So you need to update your JAXB implementation etc. to use this lib. This can be done for example by upgrading your application from `Spring Boot 2.*` to `Spring Boot 3.*`.

**Comment by BenanMozalbet** [comment]
got you, thanks
i will check again and update.

**Comment by BenanMozalbet** [comment]
changing spring version is little complicated in current time, i have a lot of relations 
is there alternative way? you said JAXB ?

**Comment by markusheiden** [comment]
I tried to make the old versions (13.0.15 and below) run with Spring Boot 3 but never got it running successfully. So I assume that the other way around is hard too. As far as I know some of the `javax.*` dependencies are incompatible with `jakarta.*`.

There are two jakarta dependencies:
jakarta.jws:jakarta.jws-api -> ???
jakarta.xml.ws:jakarta.xml.ws-api (JAXB) -> glassfish-jabx

Take a look at the Spring Boot 3 dependencies for the exact versions.

**Comment by qitia** [comment]
+ @Xinyu ***@***.***> for help double check.

Qingjun

**Comment by BenanMozalbet** [comment]
thanks , i will check.

**Comment by BenanMozalbet** [comment]
it fixed, but later in the code i got the below error:  
java.lang.NoClassDefFoundError: Could not initialize class org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl 


in general, this is my pom for BingADS artifact: 
<groupId>com.microsoft.bingads</groupId>
            <artifactId>microsoft.bingads</artifactId>
<version>13.0.16.2</version>

        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>4.0.2</version>
        </dependency>

**Comment by xinyuwen2** [comment]
It works for me to use jakarta.xml.bind 3.0.0 instead of 4.0.0. As we are using jakarta.jws 3.0.0 and jakarta.xml.ws 3.0.0 and it may causes conflict.
