### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/ws/AsyncHandler when using SDK with Java 11

### ISSUE THREAD

**Issue by nkdanta1** [BingAds/BingAds-Java-SDK#148]
**Issue Summary**
I am trying to use the Bing Ads Java SDK in my Java 11 project, but I'm getting a NoClassDefFoundError with the message javax/xml/ws/AsyncHandler. This is preventing me from using the SDK.

**Steps to Reproduce**
1. Include the Bing Ads Java SDK in a Java 11 project.
      ```
        <dependency>
                    <groupId>com.microsoft.bingads</groupId>
                    <artifactId>microsoft.bingads</artifactId>
                    <version>13.0.13</version>
        </dependency>
      ```
1. Attempt to run code that uses the SDK.
1. Observe the NoClassDefFoundError with the message javax/xml/ws/AsyncHandler.

**Comment by qitia** [comment]
I am afraind you need include additinal dependencies
```
<dependency>
    <groupId>javax.xml.ws</groupId>
    <artifactId>jaxws-api</artifactId>
    <version>2.3.1</version>
</dependency>
```

This has been removed from Java11

**Comment by nkdanta1** [comment]
Thank you for your response. I understand that the `javax.xml.ws dependency` has been removed from Java 11. Can you suggest an alternative solution that I can use in Java 11?

**Comment by qitia** [comment]
I meant you can still use that, but just include above dependency. We are working on vNext, and it will be ship soon. in which we will switch to jakarta.

**Comment by qitia** [comment]
v13.0.16.1 was released June/07. Please refer to [example](https://github.com/BingAds/BingAds-Java-SDK/blob/main/examples/BingAdsDesktopApp/pom.xml) for dependeices.
