### ISSUE TITLE
upgrade cfx to 4.0.X

### ISSUE THREAD

**Issue by schabe77** [BingAds/BingAds-Java-SDK#152]
Hello,

I'm unable to use the current 13.0.16.1. I think the problem is that you added support for jakarta for #142 , but not all your dependencies use jakarta.

The actual problem is that `jakarta.xml.ws.spi.Provider.provider()` searches for an implementation of `jakarta.xml.ws.spi.Provider`
cxf 3.4.2 contains `org.apache.cxf.jaxws.spi.ProviderImpl` but this class inherits from `javax.xml.ws.spi.Provider` and therefore isn't a valid candidate. With cxf 4 this class inherits from `jakarta.xml.ws.spi.Provider` which makes it a valid implementation.

**Comment by qitia** [comment]
fixed via 13.0.16.2
