### ISSUE TITLE
Deleted `Bid Strategy` bulk rows are not parsable

### ISSUE THREAD

**Issue by guymers** [BingAds/BingAds-Java-SDK#162]
A deleted `Bid Strategy` bulk row only contains values for the `Id`, `Parent Id` and `Status` columns so it fails to parse given the `Campaign Type` column is an empty string. I have worked around this by converting campaign types with an empty string to `null` before parsing.

**Comment by xinyuwen2** [comment]
This fix has been shipped with version 13.0.18
