### ISSUE TITLE
Why is BulkAd package private?

### ISSUE THREAD

**Issue by daangroot2** [BingAds/BingAds-Java-SDK#165]
We have a use case where we only need the `adGroupId` and `ad` from `BulkAd`, so in this case we don't care about the implementations of `BulkAd`. But since BulkAd is package private we cannot use it and have to cast the BulkAd objects to there implementation. Is there a particular reason why the BulkAd class is package private and would it be possible to make it public?

**Comment by qitia** [comment]
BulkAd is a not supposed to be used directly, you should use derived class for instance BulkProductAd.
