### ISSUE TITLE
Logging for REST-Requests

### ISSUE THREAD

**Issue by schabe77** [BingAds/BingAds-Java-SDK#186]
Do you provide a way to log the REST requests like the SOAP logging, which is described [here](https://learn.microsoft.com/en-us/advertising/guides/handle-service-errors-exceptions?view=bingads-13#java-troubleshooting)?

As far as I can see it is possible to register a jakarta.ws.rs.client.ClientRequestFilter/jakarta.ws.rs.client.ClientRequestFilter like [this one](https://github.com/kleben/jersey/blob/master/core-common/src/main/java/org/glassfish/jersey/filter/LoggingFilter.java) on the javax.ws.rs.client.Client, but I don't see anything like this at [HttpClientProvider](https://github.com/BingAds/BingAds-Java-SDK/blob/v13.0.20.1/src/main/java/com/microsoft/bingads/HttpClientProvider.java).

**Comment by dennis-yemelyanov** [comment]
If using CXF, the same logging setting `com.sun.xml.ws.transport.http.client.HttpTransportPipe.dump` works for both SOAP and REST. But some slf4 implementation needs to be added as well, more details can be found here: [Logging service calls](https://learn.microsoft.com/en-us/advertising/guides/get-started-java?view=bingads-13#logging-service-calls)

For any custom implementation we can override `HttpClientProvider` methods like `configureClientBuilder()` and register `LoggingFeature` or other filters. An example can be found here: [Customizing HTTP client](https://learn.microsoft.com/en-us/advertising/guides/get-started-java?view=bingads-13#customizing-http-client)

**Comment by schabe77** [comment]
Thank you! With your answer to #184 I managed to integrate a logger:
```
        GlobalSettings.setHttpClientProvider(new HttpClientProvider() {
            @Override
            protected ClientBuilder configureClientBuilder(ClientBuilder clientBuilder) {
                return super.configureClientBuilder(clientBuilder)
                        .register(org.glassfish.jersey.message.GZipEncoder.class)
                        .register(org.glassfish.jersey.client.filter.EncodingFilter.class)
                        .register(org.glassfish.jersey.logging.LoggingFeature.builder().verbosity(Verbosity.PAYLOAD_ANY).level(Level.FINEST).build());
            }
        });
```
