### ISSUE TITLE
ShoppingSettings.feedLabel not used / transferred

### ISSUE THREAD

**Issue by schabe77** [BingAds/BingAds-Java-SDK#200]
I was trying to set the feedLabel of a campaign's ShoppingSettings via the API, but the value just wasn't being transferred.

After some research I found out that there is no BulkMapping defined for this field in BulkCampaign.MAPPINGS, while the other values of the settings have a mapping.

Is this intentional?

**Comment by schabe77** [comment]
One more addition: ShoppingSettings.shoppableAdsEnabled is also not transferred.

**Comment by xinyuwen2** [comment]
Yes this mapping is missed and sorry for that. We'll support it in next release(September).

**Comment by xinyuwen2** [comment]
These mappings are added in version 13.0.21.2
