### ISSUE TITLE
bulk file returned group status with 'DRAFT' while the AdGroupStatus Enum don't have it

### ISSUE THREAD

**Issue by zinking** [BingAds/BingAds-Java-SDK#23]
The Bulk file returned has a 'DRAFT' group status , while the status enum don't have it. parsing it causing error.

**Comment by shyTNT** [comment]
@zinking , could you tell us what version the returned bulk file is? 3.0 or 4.0?

**Comment by zinking** [comment]
Type,Status,Id,Parent Id,Sub Type,Campaign,Ad Group,Website,Sync Time,Client Id,Modified Time,Tracking Template,Custom Parameter,Final Url,Mobile Final Url,Time Zone,Budget,Budget Type,KeywordVariantMatchEnabled,Campaign Type,Priority,Start Date,End Date,Network Distribution,Pricing Model,Ad Rotation,Search Network,Search Broad Bid,Content Network,Content Bid,Language,Title,Text,Display Url,Destination Url,Business Name,Phone Number,Promotion,Editorial Status,Editorial Location,Editorial Term,Editorial Reason Code,Editorial Appeal Status,Device Preference,Native Preference,Keyword,Match Type,Bid,Param1,Param2,Param3,Target,Physical Intent,Target All,Bid Adjustment,Radius Target Id,Name,OS Names,Radius,Unit,Business Id,From Hour,From Minute,To Hour,To Minute,Version,Sitelink Extension Order,Sitelink Extension Link Text,Sitelink Extension Destination Url,Sitelink Extension Description1,Sitelink Extension Description2,Geo Code Status,Map Icon,Business Icon,Address Line 1,Address Line 2,Postal Code,City,State Or Province Code,Province Name,Latitude,Longitude,COUNTRY_CODE,Call Only,Call Tracking Enabled,Toll Free,Alternative Text,Media Id,Publisher Countries,Store Id,Store Name,Product Condition 1,Product Value 1,Product Condition 2,Product Value 2,Product Condition 3,Product Value 3,Product Condition 4,Product Value 4,Product Condition 5,Product Value 5,Product Condition 6,Product Value 6,Product Condition 7,Product Value 7,Product Condition 8,Product Value 8,Callout Text,Action Text,Action Link Url,Is Exact,Source,Url,Structured Snippet Category,Structured Snippet Texts,Spend,Impressions,Clicks,CTR,Avg CPC,Avg CPM,Avg position,Conversions,CPA,Quality Score,Keyword Relevance,Landing Page Relevance,Landing Page User Experience,App Platform,App Id,Tracking Enabled,App Status,Error,Error Number,Is Excluded,Parent Criterion Id
Format Version,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Account,,4xxxx0183,1xxxx0100,,,,,04/29/2016 01:31:03,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Ad Group,Draft,485xxxxx53,191879116,,TestU2,Ad group #1,,,,04/26/2016 01:58:34.000,,,,,,,,,,,04/25/2016,,OwnedAndOperatedAndSyndicatedSearch,CPC,OptimizeForClicks,On,0.05,On,0.05,English,,,,,,,,,,,,,,,,,,,,,

hope this helps.

**Comment by shyTNT** [comment]
Thanks for your information. Your bulk file format was 3.0 which supported the "DRAFT" status in AdGroupStatus(v9). Howerver this status was removed in the format 4.0 of bulk file.And the AdGroupStatus(v10) don't have this status any more. Hope this helps for you.

**Comment by dennis-yemelyanov** [comment]
@zinking , did you download the file using com.microsoft.bingads.bulk.BulkServiceManager? If so, make sure that for parsing you use classes from the same package, such as com.microsoft.bingads.bulk.BulkFileReader. The classes from the v10 package (com.microsoft.bingads.v10.bulk) may not parse bulk files downloaded using the previous version.

**Comment by zinking** [comment]
yeah, it looks I've mixed these different versions up, strange thing is I can download v10 contents with v9 api. (upgraded url fields). I am updating code to all v10 based. will close the issue once confirming this.

**Comment by zinking** [comment]
@dennis-yemelyanov @shyTNT  
    
     import com.microsoft.bingads.bulk.BulkServiceManager;

is this package what you call v9?

**Comment by MingfeiJia** [comment]
@zinking, yes, that is the v9 package.
