### ISSUE TITLE
Bad format for CustomParameters: delete_value

### ISSUE THREAD

**Issue by mhuang74** [BingAds/BingAds-Java-SDK#32]
Looks like SDK code inserts "delete_value" token, which then it is unable to parse. StringExtensions.toCustomParaBulkString() and StringExtensions.parseCustomParameters() are not in agreement.

[StringExtensions.toCustomParaBulkString()](https://github.com/BingAds/BingAds-Java-SDK/blob/f587f6c20b16bd4ee6e4bb6d50c40ed841b7bf7e/src/main/java/com/microsoft/bingads/v10/internal/bulk/StringExtensions.java#L611)

[StringExtensions.parseCustomParameters()](https://github.com/BingAds/BingAds-Java-SDK/blob/f587f6c20b16bd4ee6e4bb6d50c40ed841b7bf7e/src/main/java/com/microsoft/bingads/v10/internal/bulk/StringExtensions.java#L673)

java.lang.IllegalArgumentException: Bad format for CustomParameters: delete_value
    at com.microsoft.bingads.v10.internal.bulk.StringExtensions.parseCustomParameters(StringExtensions.java:656)
    at com.microsoft.bingads.v10.bulk.entities.BulkKeyword$34.accept(BulkKeyword.java:358)
    at com.microsoft.bingads.v10.bulk.entities.BulkKeyword$34.accept(BulkKeyword.java:354)

**Comment by shyTNT** [comment]
@mhuang74 , thanks for your comment. SDK will insert "delete_value" into the bulk file if users want to delete the CustomParameters. I think maybe you parse the bulk file before you upload it. Could you please provide the scenario information of this issue?
