### ISSUE TITLE
BulkEntityIterable is only an Iterator

### ISSUE THREAD

**Issue by Pearl2Jam** [BingAds/BingAds-Java-SDK#5]
BulkEntityIterable sounds and looks like you could traverse all items more than once, but in the end its only an iterator. thats really confusing

**Comment by dennis-yemelyanov** [comment]
Thanks! There are similar classes in the standard Java library that allow only one pass, for example [DirectoryStream](http://docs.oracle.com/javase/7/docs/api/java/nio/file/DirectoryStream.html). However I agree that the name could be more transparent.

**Comment by freiz** [comment]
I don't think Iterator implies traverse all items more than once, which depends on implementation. In general, the one-pass design, such as the generator pattern. As a library, it cannot make decision for user to save all the entities in one collection, think about scenario parsing 100GB bulk file, it cannot be fitted into memory.

generator pattern and lazy evaluation is always more faster, resource friendly and elegant, think about this scenario 

``` haskell
take 100 [1..]
```

it cannot be done without generator.

And of course, if you know the data well, you can still first walk through the iterator and save into collections you like.
