### ISSUE TITLE
Introduce public non-internal constant for "delete_value"

### ISSUE THREAD

**Issue by markus-s24** [BingAds/BingAds-Java-SDK#50]
I would be nice if there is a public non-internal constant for "delete_value", with good documentation how to use it. Furthermore it would be nice, if all fields that support "delete_value" get a Javadoc link to it.

**Comment by eric-urban** [comment]
Hi @markus-s24 

Do you have more detail on the workflow that requires a documented list of all places where delete_value could be used? The Bulk schema documentation e.g. [Keyword record](https://msdn.microsoft.com/en-us/library/bing-ads-bulk-keyword-record.aspx) mentions where delete_value is applicable. Depending on which record you are working with, please refer to the corresponding reference doc. If there are any misses in the service documentation, please let me know and we will update the docs right away. 

For the public constant we will investigate options. 

Thanks,
Eric

**Comment by eric-urban** [comment]
@markus-s24 although it is in the internal namespace (```import com.microsoft.bingads.internal.StringTable;```) would [StringTable.DeleteValue](https://github.com/BingAds/BingAds-Java-SDK/blob/e457560d18d6c53ca23ffc80b86dca18f71c0728/src/main/java/com/microsoft/bingads/internal/StringTable.java#L262) work for you?

**Comment by eric-urban** [comment]
@markus-s24 please reopen if StringTable.DeleteValue does not satisfy the request. Thanks!
