### ISSUE TITLE
Include a program to generate the refresh token.

### ISSUE THREAD

**Issue by sixcorners** [BingAds/BingAds-Java-SDK#61]
Please include a program that can be used to generate the refresh token [like google did with their java client library](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/auth/GetRefreshToken.java). I've been generating the refresh token once then deploying software with it to periodically run reports.

**Comment by eric-urban** [comment]
Have you tried the [OAuthDesktopApplication](https://github.com/BingAds/BingAds-Java-SDK/blob/master/examples/BingAdsDesktopApp/src/main/java/com/microsoft/bingads/examples/v11/OAuthDesktopApplication.java) sample? Also note per the [getting started guide](https://msdn.microsoft.com/en-us/library/bing-ads-overview-getting-started-java-with-web-services.aspx#oauth) that when calling Bing Ads services with ServiceClient, BulkServiceManager, or ReportingServiceManager, each instance will refresh your access token automatically if they detect the AuthenticationTokenExpired (109) error code. It is important to save the most recent refresh token whenever new OAuth tokens are received. You will want to implement event handling using the NewOAuthTokensReceivedListener.

**Comment by aj07mm** [comment]
I'm having the same issue, couldn't find a way to generate the refresh token after expiration without the need to open a browser and type the credentials then paste it back. Everything happens on this line: `webbrowser.open(auth_data.authentication.get_authorization_endpoint(), new=1)`
