### ISSUE TITLE
Add ability to make GeographicalLocationReportRequest with "HOURLY" aggregation option.

### ISSUE THREAD

**Issue by LexGoo** [BingAds/BingAds-Java-SDK#63]
On web side the GeographicalLocationReportRequest can be created with hourly aggregation. 

It would be an advantage to get reports from API with a hourly aggregation for GeographicalLocationReportRequest.

**Comment by eric-urban** [comment]
Thanks for the feedback. Currently the reporting service does not include Hourly aggregation for a few reports. Once the reporting service is updated, the SDK can also be updated to reflect the same. I've submitted this request to the Reporting service team, and will let you know once we have an ETA.

(_Note_: In version 11, the UserLocationPerformanceReportRequest with corresponding columns and filter replaces the GeographicalLocationReportRequest. )

**Comment by eric-urban** [comment]
@LexGoo support for Hourly is added to Reporting API [Version 12](https://docs.microsoft.com/en-us/bingads/guides/migration-guide?view=bingads-12#reporting-reportaggregation). Thanks for your patience!
