### ISSUE TITLE
Migrating v10 to v11

### ISSUE THREAD

**Issue by pocin** [BingAds/BingAds-Java-SDK#68]
Hi guys, there is a library built on top of this v10 sdk (https://github.com/davidesner/keboola-bingads-ex). I'd like to port it to the v11, do you have any experience with the compatibility? I've read the changelog, but I found it hard to assess the implications to this sdk. Would simply changing the imports from 

```java
import com.microsoft.bingads.v10.bulk.BulkDownloadEntity;
import com.microsoft.bingads.v10.bulk.BulkOperationProgressInfo;
import com.microsoft.bingads.v10.bulk.BulkServiceManager;
import com.microsoft.bingads.v10.bulk.DataScope;
import com.microsoft.bingads.v10.bulk.DownloadFileType;
import com.microsoft.bingads.v10.bulk.DownloadParameters;
import com.microsoft.bingads.v10.bulk.Progress;
```

to

```java
import com.microsoft.bingads.v11.bulk.BulkDownloadEntity;
import com.microsoft.bingads.v11.bulk.BulkOperationProgressInfo;
import com.microsoft.bingads.v11.bulk.BulkServiceManager;
import com.microsoft.bingads.v11.bulk.DataScope;
import com.microsoft.bingads.v11.bulk.DownloadFileType;
import com.microsoft.bingads.v11.bulk.DownloadParameters;
import com.microsoft.bingads.v11.bulk.Progress;
```

or something along the lines work, or you expect some issues?

**Comment by eric-urban** [comment]
@pocin I have not looked into keboola-bingads-ex. Strictly speaking to the Bing Ads Java SDK migration from v10 to v11 the changes you mentioned look correct - except you should use DownloadEntity in v11 instead of BulkDownloadEntity. I hope this helps!

**Comment by pocin** [comment]
Thank you, Eric. I'll give it a shot.
