### ISSUE TITLE
Classes don't have constructors with parameters

### ISSUE THREAD

**Issue by juliccr** [BingAds/BingAds-Java-SDK#69]
Hi, I'd like to know why is it that the domain classes (for instance, [CampaignScope](https://github.com/BingAds/BingAds-Java-SDK/blob/master/proxies/com/microsoft/bingads/v11/bulk/CampaignScope.java)) only have the default constructor and do not have the constructor with the parameters. The creation of some objects using `setters` turns quite cumbersome sometimes. Moreover, if we need to create an object and forget setting something, we would be breaking the object's invariant.

Are these classes autogenerated? If they are, where is the code that generates them?  What do you think of opening a PR with the default constructors and also the constructors with parameters? 

Thanks!

**Comment by eric-urban** [comment]
Yes these are automatically generated i.e., [here](https://github.com/BingAds/BingAds-Java-SDK/blob/master/proxies/generateAllServiceProxies.bat). Its a good suggestion, and we'll investigate what options are feasible.

**Comment by juliccr** [comment]
Ok, thank you @eric-urban
