### ISSUE TITLE
GeographicPerformanceReportColumn Value Set does not match Java Bing SDK 

### ISSUE THREAD

**Issue by csarmiento** [BingAds/BingAds-Java-SDK#71]
The fields available for the Geographic Performance Report are not matching the ones in the enumeration.

I checked the documentation [here](https://msdn.microsoft.com/library/bing-ads-reporting-geographicperformancereportcolumn.aspx), against the fields listed in the Enum [here](https://github.com/BingAds/BingAds-Java-SDK/blob/master/proxies/com/microsoft/bingads/v11/reporting/GeographicPerformanceReportColumn.java).

The following fields are missing from the enum:

- "County"
- "PostalCode"
- "LocationId"

**Comment by eric-urban** [comment]
@csarmiento these columns will be available in the next release i.e., early November. Thanks for your patience!

**Comment by eric-urban** [comment]
@csarmiento the SDK has been updated.
