### ISSUE TITLE
Missing columns in KeywordPerformanceReportColumns.java

### ISSUE THREAD

**Issue by juliccr** [BingAds/BingAds-Java-SDK#73]
Hi, we were trying to download `Mainline1Bid` and `MainlineBid` columns (specified [here](https://docs.microsoft.com/en-us/bingads/reporting-service/keywordperformancereportcolumn) ) for the KeywordPerformanceReport using the SDK but there are not present in the enum 
[KeywordPerformanceReportColumn.java](https://github.com/BingAds/BingAds-Java-SDK/blob/master/proxies/com/microsoft/bingads/v11/reporting/KeywordPerformanceReportColumn.java) . 

- Can they be included? 

- Is there another way to obtain those values using the SDK despite their absence in the enum? 

Thanks !

**Comment by eric-urban** [comment]
Hello.

We plan to include these with the December SDK release. In the meantime you could opt to generate a private build. Here are the high level steps:

1. Clone from GitHub i.e., git clone https://github.com/BingAds/BingAds-Java-SDK.git
2. Build this solution: https://github.com/BingAds/BingAds-Java-SDK/tree/master/tools/WsdlEnumGenerator 
3. Run https://github.com/BingAds/BingAds-Java-SDK/blob/master/proxies/generateAllServiceProxies.bat
4. Build the SDK project

I hope this helps.

**Comment by qitia** [comment]
close this issue as the columns have been included since version 11.5.7. @juliccr Please reopen this if you have more questions.
