### ISSUE TITLE
Security vulnerabilities in linked libraries

### ISSUE THREAD

**Issue by SaraRands** [BingAds/BingAds-Java-SDK#74]
Our security team is showing that some of your dependent libraries have security vulnerabilities and should be updated to the latest version. Blackduck shows that the following libraries have vulnerabilities:

org.apache.cxf » cxf-rt-frontend-jaxws | 3.0.2
org.apache.cxf » cxf-rt-transports-http | 3.0.2
org.apache.httpcomponents » httpmime | 4.0.1

Can you update these libraries to the latest version to remove these vulnerabilities?

**Comment by eric-urban** [comment]
@SaraRands thank you for flagging this issue! We are planning to upgrade to cxf 3.0.15 and http 4.5.3 in the next release.

**Comment by qitia** [comment]
the libs has been upgraded since 11.5.7
cxf from 3.0.2 to 3.0.15
httpclient and httpmime from 4.0.1 to 4.5.3

**Comment by qitia** [comment]
close it and please reopen if you have more questions @SaraRands
