### ISSUE TITLE
Not returning Id when creating a new campaign location criterion

### ISSUE THREAD

**Issue by ptdang** [BingAds/BingAds-Java-SDK#75]
Hello,

we are using the Bulk Service to create campaign location criterions and notice that the Id is returned in the response like Campaigns or Keywords.

https://docs.microsoft.com/en-us/bingads/bulk-service/campaign-location-criterion#id

Is this a bug in the SDK?

**Comment by eric-urban** [comment]
@ptdang I am not able to repro this issue. I see the Id in the upload result file and it is also populated in the BulkCampaignLocationCriterion object. Do you see the Id in the upload result file but it is not populated in the BulkCampaignLocationCriterion object, or can you please describe more about the repro steps? It might help to [contact support](https://advertise.bingads.microsoft.com/en-us/bing-ads-support) and provide the download request ID + time stamp for investigation.

**Comment by ptdang** [comment]
hi eric,
I reached out to account management and have figured out a work around. The issue was that we were not explicitly including the "Id" column in the bulk upload file for our creates.
