### ISSUE TITLE
BulkServiceManager's downloadEntitiesAsync doesn't handle error 117 correctly

### ISSUE THREAD

**Issue by scampiuk** [BingAds/BingAds-Java-SDK#78]
When making an async download request, if  any of the polls for the status of the download trigger a 117- CallRateExceeded error, the entire download fails, however the download would be fine if the status poll could be retried.

It should ether wait a given time before trying again, or provide some way of defining what to do for given error codes.

**Comment by eric-urban** [comment]
@scampiuk great suggestion, thanks! We will discuss it and get back to you.

**Comment by qitia** [comment]
@scampiuk  we implement this feature in version 11.12.2. See https://github.com/BingAds/BingAds-Java-SDK/blob/2539cdd7620ef2e5ac3e3e950c2ef081daee2efa/src/main/java/com/microsoft/bingads/internal/OperationStatusRetry.java#L18 for detail.
