### ISSUE TITLE
BulkAccount missing supported fields

### ISSUE THREAD

**Issue by jonroler** [BingAds/BingAds-Java-SDK#80]
The BulkAccount class for both v11 and v12 appears to be missing 2 fields that are returned by the bulk API call: "MSCLKID Auto Tagging Enabled" and "Tracking Template". I've verified that these fields are returned in the file returned by the bulk API as documented for v11 here: https://docs.microsoft.com/en-us/bingads/bulk-service/account?view=bingads-11#msclkidautotaggingenabled and for v12 here: https://docs.microsoft.com/en-us/bingads/bulk-service/account?view=bingads-12#msclkidautotaggingenabled, but they simply aren't exposed by the BulkAccount class. This appears to be an oversight in the Bing Ads java sdk. Could you please add support for these fields? The field I currently care about is "MSCLKID Auto Tagging Enabled", so if adding support for the "Tracking Template" field slows things down for some reason, then please add support for the "MSCLKID Auto Tagging Enabled" field first and release. Also, we are still on version v11 of the API, so please add support for these fields to both v11 and v12.

**Comment by qitia** [comment]
thanks for reaching out @jonroler . We will look into this and come back.

**Comment by qitia** [comment]
Thanks @jonroler the missing attributes have added since version 11.12.3. I will close this issue and let me know if you have more concern.
