### ISSUE TITLE
Create enumerations for DeviceName

### ISSUE THREAD

**Issue by davidklebanoff** [BingAds/BingAds-Java-SDK#89]
Create an enum for all the deviceName options for use in the `DeviceCriterion`. Similar to how `IntentOption` is used by `LocationIntentCriterion`.

- All
- Computers
- Smartphones
- Tablets

**Comment by eric-urban** [comment]
@davidklebanoff thanks for the suggestion, although the SDK proxies match the WSDL definition e.g., string for [DeviceName](https://docs.microsoft.com/en-us/bingads/campaign-management-service/devicecriterion?view=bingads-12#devicename). In many cases string is used for flexibility i.e., to add new values without causing serialization errors for older clients. With intent option there is some confidence the value set won't be expanded, or might only be expanded in a new API version.
