### ISSUE TITLE
Unable to download specific account's report

### ISSUE THREAD

**Issue by sureshbabuinfo** [BingAds/BingAds-Java-SDK#96]
I am managing multiple accounts under a single developer token. When I download `campaignperformancereport` or `keywordperformancereport` it downloads the report for all the accounts I manage. There is no option to filter specific accounts.

**Comment by qitia** [comment]
@sureshbabuinfo did you try below?

        final CampaignPerformanceReportRequest req = new CampaignPerformanceReportRequest();
        AccountThroughCampaignReportScope scope = new AccountThroughCampaignReportScope();
        ArrayOflong accountIds = new ArrayOflong();
        accountIds.getLongs().add(SomeAccountIds);
        scope.setAccountIds(accountIds);
        req.setScope(scope);
        ...
